version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - corepack enable
      - pnpm install

  build:
    commands:
      - pnpm --filter server build

  post_build:
    commands:
      - echo Build finished

artifacts:
  files:
    - './server/dist/**/*'
